
stages:
  remove_topics:
    foreach: ${speeches}
    do:
      cmd: python src/remove_topics.py --data data/raw/${item}.txt --dest data/without_topics/${item}.txt --params params.yaml --topics topics
      deps:
        - src/remove_topics.py
        - data/raw/${item}.txt
      outs:
        - data/without_topics/${item}.txt
      params:
        - topics
