
stages:
  remove_topics:
    foreach: ${speeches}
    do:
      cmd: python src/remove_topics.py --data data/raw/${item} --dest data/without_topics/${item} --params params.yaml --topics topics
      deps:
        - src/remove_topics.py
        - data/raw/${item}
      outs:
        - data/without_topics/${item}
      params:
        - topics
  remove_orphan_new_lines:
    foreach: ${speeches}
    do:
      cmd: python src/remove_orphan_new_lines.py --data data/without_topics/${item} --dest data/no_orphans/${item} --params params.yaml --topics topics
      deps:
        - src/remove_topics.py
        - data/raw/${item}
      outs:
        - data/without_topics/${item}
      params:
        - topics