topics:
  - "Preventing Future Terrorist Attacks"
  - "Likelihood of Future Terrorist Attack"
  - "President's Judgment on Foreign Policy"
  - "Priorities in the War on Terror"
  - "Homeland Security"
  - "Criteria for Withdrawal of U.S. Troops From Iraq"
  - "Postwar Iraq"
  - "Candidates' Candor and Consistency"
  - "Hard Decisions/Support for the Military"
  - "Timeline for Withdrawal From Iraq/ Conditions in Iraq"
  - "Future U.S. Military Action"
  - "Preemptive Action/International Cooperation"
  - "North Korea and Iran"
  - "Iran/Sudan"
  - "Character of the Candidates"
  - "Nuclear Proliferation"
  - "President Vladimir Putin of Russia"
  - "Closing Statements"
  - "(Applause)"

speeches:
  #- 2000_10_03_bush_gore.txt
  - 2000_10_11_bush_gore.txt
  - 2000_10_17_bush_gore.txt
  - 2004_09_30_bush_kerry.txt
  - 2004_10_08_bush_kerry.txt
  - 2004_10_13_bush_kerry.txt
  - 2008_09_26_mccain_obama.txt
  - 2008_10_07_mccain_obama.txt
  - 2008_10_15_mccain_obama.txt
  - 2012_10_03_romney_obama.txt
  - 2012_10_16_romney_obama.txt
  - 2012_10_22_romney_obama.txt
  - 2016_09_26_trump_clinton.txt
  - 2016_10_09_trump_clinton.txt
  - 2016_10_19_trump_clinton.txt
  - 2020_09_29_trump_biden.txt
  - 2020_10_22_trump_biden.txt