topics:
  - "Preventing Future Terrorist Attacks"
  - "Likelihood of Future Terrorist Attack"
  - "President's Judgment on Foreign Policy"
  - "Priorities in the War on Terror"
  - "Homeland Security"
  - "Criteria for Withdrawal of U.S. Troops From Iraq"
  - "Postwar Iraq"
  - "Candidates' Candor and Consistency"
  - "Hard Decisions/Support for the Military"
  - "Timeline for Withdrawal From Iraq/ Conditions in Iraq"
  - "Future U.S. Military Action"
  - "Preemptive Action/International Cooperation"
  - "North Korea and Iran"
  - "Iran/Sudan"
  - "Character of the Candidates"
  - "Nuclear Proliferation"
  - "President Vladimir Putin of Russia"
  - "Closing Statements"
